version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:426065088228:task-definition/DEMOO:1"  
        LoadBalancerInfo:
          ContainerName: "demooo"
          ContainerPort: 8080:8080