version: 0.2

env:
  variables:
    APP_NAME: "my-spring-boot-app"
    AWS_REGION: "us-east-1"
    ECR_REPOSITORY_URI: "426065088228.dkr.ecr.us-east-1.amazonaws.com/newrepo"
    ECS_CLUSTER_NAME: "Demoo"
    ECS_SERVICE_NAME: "demoop"
  parameter-store:
    AWS_ACCESS_KEY_ID: "/CodeBuild/ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "/CodeBuild/SECRET_ACCESS_KEY"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y jq
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 426065088228.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn package
      - docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' "$APP_NAME" "$ECR_REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - target/*.jar